name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [{{ cookiecutter.project_python_ci }}]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python }}{% endraw %}
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        pip install tox
    - name: Run Tox
      run: |
        source $HOME/.poetry/env
        tox -e py
